services:
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
    restart: always
    depends_on:
      - ngrok
      - redis
      - notification
    networks:
      - app-network

  ngrok:
    image: wernight/ngrok
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTH=${NGROK_AUTH_TOKEN}
      - NGROK_PORT=web:5001
      - --region=ap
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis-data:/data

  notification:
    build:
      context: .
      dockerfile: Dockerfile.notification
    ports:
      - "5002:5002"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - BACKEND_URL=http://web:5001
    volumes:
      - ./notification:/app
    networks:
      - app-network
    depends_on:
      - redis

networks:
  app-network:
    driver: bridge

volumes:
  redis-data: