services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly no --save ""  # 無効なオプションを削除
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  web:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./backend:/app
    depends_on:
      redis:
        condition: service_healthy
    restart: always
    networks:
      - app-network

  notification:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5002:5002"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - BACKEND_URL=http://web:5001
    volumes:
      - ./frontend:/app
    depends_on:
      redis:
        condition: service_healthy
      web:
        condition: service_started
    restart: always
    networks:
      - app-network

  ngrok:
    image: ngrok/ngrok:latest
    ports:
      - "4040:4040"
    env_file:
      - .env
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTH_TOKEN}
    command: 
      - "http"
      - "web:5001"
      - "--log"
      - "stdout"
    networks:
      - app-network
    depends_on:
      web:
        condition: service_started

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
    driver: local